///
/// \file VTPDelegate.h
///

#ifndef VTPDelegate_h
#define VTPDelegate_h

#import "VTPStatus.h"
#import "VTPBluetoothDevice.h"
#import "VPDPairingConfirmationCallback.h"
#import "VTPDeviceSetupResult.h"

///
/// \protocol VTPDelegate
///
/// \brief Protocol for the device notifications
///
/// The VTPDelegate protocol defines the methods a receiver may implement for device notifications.
///
@protocol VTPDelegate

@optional

///
/// \brief Device connected callback
///
/// This protocol method is called to inform the delegate a recognized device has been connected.
///
/// \param description The description of the connected device.
///
/// \param model The model of the connected device.
///
/// \param serialNumber The serial number of the connected device. This value may be nil if the connected device does not supply this value. In some cases, this value may not be available immediately upon connection.
///
-(void)deviceDidConnect:(NSString *)description model:(NSString *)model serialNumber:(NSString *)serialNumber;

///
/// \brief Device connected callback with firmware and configuration version
///
/// This protocol method is called to inform the delegate a recognized device has been connected.
///
/// \param description The description of the connected device.
///
/// \param model The model of the connected device.
///
/// \param serialNumber The serial number of the connected device. This value may be nil if the connected device does not supply this value. In some cases, this value may not be available immediately upon connection.
///
/// \param firmwareVersion The firmware version of the connected device.
///
/// \param configurationVersion The configuration/settings version of the connected device. This value may be nil if the connected device does not supply this value. 
///
/// \param batteryPercentage The battery percentage of the connected device.
///
/// \param batteryLevel The battery level of the connected device.
///
-(void)deviceDidConnect:(NSString *)description model:(NSString *)model serialNumber:(NSString *)serialNumber firmwareVersion:(NSString*) firmwareVersion configurationVersion:(NSString*) configurationVersion batteryPercentage:(NSString*) batteryPercentage batteryLevel:(NSString*) batteryLevel;

///
/// \brief Device disconnected callback
///
/// This protocol method is called to inform the delegate the device has been disconnected.
///
-(void)deviceDidDisconnect;

///
/// \brief Device connection progress callback
///
/// This protocol method is called to inform the delegate a recognized device has been connected - but that initialization is in progress.
///
/// \param currentProgress The percentage completed for device initialization.
///
/// \param description The description of the device being initialized.
///
/// \param model The model of the device being initialized.
///
/// \param serialNumber The serial number of the device being initialized. This value may be nil if the connected device does not supply this value. In some cases, this value may not be available immediately upon connection.
///
/// \param currentStep The current initialization step.
///
-(void)deviceInitializationInProgress:(double) currentProgress description:(NSString *)description model:(NSString *)model serialNumber:(NSString *)serialNumber currentStep:(NSString*) currentStep;

///
/// \brief Device initialization progress callback with progress percentage and current status
///
/// Updated the device on the progress of device initialization
///
/// \param currentProgress The percentage completed for device initialization.
///
/// \param description The description of the device being initialized.
///
/// \param model The model of the device being initialized.
///
/// \param serialNumber The serial number of the device being initialized. This value may be nil if the connected device does not supply this value. In some cases, this value may not be available immediately upon connection.
///
/// \param initializationStatus The current initialization status
-(void) deviceInitializationInProgress:(double) currentProgress description:(NSString *)description model:(NSString *)model serialNumber:(NSString *)serialNumber initializationStatus:(VTPInitializationStatus) initializationStatus;

///
/// \brief Device error callback
///
/// This protocol method is called to inform the delegate the device generated an error. This notification is only generated for errors occuring outside functionality explicitly invoked by the integrator. For example, if the device connects, but an error occurs during initialization, this method is called. However, if something like a sale is started or card input is enabled, any errors are reported through the mechanisms defined by those methods.
///
/// \param error The error generated by the device.
///
-(void)deviceDidError:(NSError *)error;


///
/// \brief Status callback
///
/// This protocol method is called to inform the delegate the SDK's status has changed. Currently the status is changed during initialization and during operations like sale or refund. However, the status is not changed during direct operations like the integrator enabling card input directly or making a direct call to Express.
///
/// \param status The current status.
///
/// \param description The description of the current status.
///
-(void)statusDidChange:(VTPStatus)status description:(NSString *)description;


///
/// \brief Low battery callback
///
/// This protocol method is called to inform the delegate the the connected device's battery level is low. ///
///
-(void)onBatteryLow;

//
/// \brief Pre-read data timed out.
///
/// This protocol method is called to inform the delegate that the most recently pre-read data has timed out and will be
/// removed from memory.
///
-(void)prereadTimedOut;

//
/// \brief Returns a list of scanned devices.
///
/// Returns a list of the available devices of the specified device type in the configuration.
///
/// \param devices List of identifiers of available devices.
///
///
-(void) onReturnBluetoothScanResults:(NSArray<VTPBluetoothDevice*>*) devices;

///
/// \brief Informs the delegate of a warning that may lead to degraded operation of the SDK.
///
/// This protocol method is called to inform the delegate of a warning that may lead to degraded
/// operation of the SDK, for example, no EMV.
///
/// \param warning The text of the warning.
///
-(void)onWarning:(NSString *)warning;

///
/// \brief Moby device pairing confiramtion
///
/// This method returns device pairing confirmation callback
///

-(void) onReturnPairingConfirmation:(NSArray*) ledSequence deviceName:(NSString*) deviceName callback:(id<VPDPairingConfirmationCallback>) callback;


///
/// \brief Device connected callback with firmware and configuration version
///
/// This protocol method is called to inform the delegate a recognized device has been connected.
///
/// \param description The description of the connected device.
///
/// \param model The model of the connected device.
///
/// \param serialNumber The serial number of the connected device. This value may be nil if the connected device does not supply this value. In some cases, this value may not be available immediately upon connection.
///
/// \param firmwareVersion The firmware version of the connected device.
///
/// \param configurationVersion The configuration/settings version of the connected device. This value may be nil if the connected device does not supply this value.
///
/// \param batteryPercentage The battery percentage of the connected device.
///
/// \param batteryLevel The battery level of the connected device.
///
/// \param deviceDescription The description\identifier for the device as provided in the device pool
///
/// \param address The IPAddress:Port number for the connected device
///
/// The method returns the details of the device configured during device pool setup
///
-(void) onDeviceSetupCompleted:(NSString *)description model:(NSString *)model serialNumber:(NSString *)serialNumber firmwareVersion:(NSString*) firmwareVersion configurationVersion:(NSString*) configurationVersion batteryPercentage:(NSString*) batteryPercentage batteryLevel:(NSString*) batteryLevel deviceDescription:(NSString *)deviceDescription address:(NSString *)address;

///
/// \brief Indicates the device setup from device pool failed
///
/// \param deviceDescription The description\identifier for the device as provided in the device pool
///
/// \param address The IPAddress:Port number for the connected device
///
/// The method indicates the connection\configuration of the device from the device pool failed
///
-(void)onDeviceSetupError:(NSError *)error deviceDescription:(NSString *)deviceDescription address:(NSString *)address;


///
/// \brief Device pool configuration completion callback with summary of the result.
///
/// \param deviceResult Summary of the device pool configuration with results for each device in the device pool.
///
/// This method returns the device pool setup completion callback with the details of each device in the device pool along with the status of the connection\configuration
///
-(void)onDevicePoolSetupCompleted:(NSArray<VTPDeviceSetupResult *> *) deviceResult;

typedef void (^VTPConfirmConfigureonStartSession)(BOOL yes);


///
/// \brief Callback to confirm if the device needs to be configured during a start session.
///
/// \param message : Message to be displayed to the user.
///
/// \param callback: Delegate to send back the user confirmation to proceed with the configuration.
///
/// This method sends a request to confirm if the device needs to be configured during the start session operation.
///
/// <br /><br /><strong>NOTE:</strong> Based on the confirmation sent back through the delegate, the device will be configured before the session is established or if declined the start session operation will be aborted.
///
-(void)onConfirmConfigureDeviceOnStartSession:(NSString *)message callback:(VTPConfirmConfigureonStartSession)callback;


@end

#endif /* VTPDelegate_h */
